// <auto-generated />
using System;
using Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ParkingApp2Server.Migrations
{
    [DbContext(typeof(RepositoryContext))]
    partial class RepositoryContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.4");

            modelBuilder.Entity("DayTenant", b =>
                {
                    b.Property<string>("DaysDayId")
                        .HasColumnType("nvarchar(4)");

                    b.Property<string>("TenantsTenantId")
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("DaysDayId", "TenantsTenantId");

                    b.HasIndex("TenantsTenantId");

                    b.ToTable("DayTenant");
                });

            modelBuilder.Entity("Entities.Models.Day", b =>
                {
                    b.Property<string>("DayId")
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)");

                    b.HasKey("DayId");

                    b.ToTable("Days");

                    b.HasData(
                        new
                        {
                            DayId = "0101"
                        },
                        new
                        {
                            DayId = "0201"
                        },
                        new
                        {
                            DayId = "0301"
                        },
                        new
                        {
                            DayId = "0401"
                        },
                        new
                        {
                            DayId = "0501"
                        },
                        new
                        {
                            DayId = "0601"
                        },
                        new
                        {
                            DayId = "0701"
                        },
                        new
                        {
                            DayId = "0801"
                        },
                        new
                        {
                            DayId = "0901"
                        },
                        new
                        {
                            DayId = "1001"
                        },
                        new
                        {
                            DayId = "1101"
                        },
                        new
                        {
                            DayId = "1201"
                        },
                        new
                        {
                            DayId = "1301"
                        },
                        new
                        {
                            DayId = "1401"
                        },
                        new
                        {
                            DayId = "1501"
                        },
                        new
                        {
                            DayId = "1601"
                        },
                        new
                        {
                            DayId = "1701"
                        },
                        new
                        {
                            DayId = "1801"
                        },
                        new
                        {
                            DayId = "1901"
                        },
                        new
                        {
                            DayId = "2001"
                        },
                        new
                        {
                            DayId = "2101"
                        },
                        new
                        {
                            DayId = "2201"
                        },
                        new
                        {
                            DayId = "2301"
                        },
                        new
                        {
                            DayId = "2401"
                        },
                        new
                        {
                            DayId = "2501"
                        },
                        new
                        {
                            DayId = "2601"
                        },
                        new
                        {
                            DayId = "2701"
                        },
                        new
                        {
                            DayId = "2801"
                        },
                        new
                        {
                            DayId = "2901"
                        },
                        new
                        {
                            DayId = "3001"
                        },
                        new
                        {
                            DayId = "3101"
                        },
                        new
                        {
                            DayId = "0102"
                        },
                        new
                        {
                            DayId = "0202"
                        },
                        new
                        {
                            DayId = "0302"
                        },
                        new
                        {
                            DayId = "0402"
                        },
                        new
                        {
                            DayId = "0502"
                        },
                        new
                        {
                            DayId = "0602"
                        },
                        new
                        {
                            DayId = "0702"
                        },
                        new
                        {
                            DayId = "0802"
                        },
                        new
                        {
                            DayId = "0902"
                        },
                        new
                        {
                            DayId = "1002"
                        },
                        new
                        {
                            DayId = "1102"
                        },
                        new
                        {
                            DayId = "1202"
                        },
                        new
                        {
                            DayId = "1302"
                        },
                        new
                        {
                            DayId = "1402"
                        },
                        new
                        {
                            DayId = "1502"
                        },
                        new
                        {
                            DayId = "1602"
                        },
                        new
                        {
                            DayId = "1702"
                        },
                        new
                        {
                            DayId = "1802"
                        },
                        new
                        {
                            DayId = "1902"
                        },
                        new
                        {
                            DayId = "2002"
                        },
                        new
                        {
                            DayId = "2102"
                        },
                        new
                        {
                            DayId = "2202"
                        },
                        new
                        {
                            DayId = "2302"
                        },
                        new
                        {
                            DayId = "2402"
                        },
                        new
                        {
                            DayId = "2502"
                        },
                        new
                        {
                            DayId = "2602"
                        },
                        new
                        {
                            DayId = "2702"
                        },
                        new
                        {
                            DayId = "2802"
                        },
                        new
                        {
                            DayId = "2902"
                        },
                        new
                        {
                            DayId = "0103"
                        },
                        new
                        {
                            DayId = "0203"
                        },
                        new
                        {
                            DayId = "0303"
                        },
                        new
                        {
                            DayId = "0403"
                        },
                        new
                        {
                            DayId = "0503"
                        },
                        new
                        {
                            DayId = "0603"
                        },
                        new
                        {
                            DayId = "0703"
                        },
                        new
                        {
                            DayId = "0803"
                        },
                        new
                        {
                            DayId = "0903"
                        },
                        new
                        {
                            DayId = "1003"
                        },
                        new
                        {
                            DayId = "1103"
                        },
                        new
                        {
                            DayId = "1203"
                        },
                        new
                        {
                            DayId = "1303"
                        },
                        new
                        {
                            DayId = "1403"
                        },
                        new
                        {
                            DayId = "1503"
                        },
                        new
                        {
                            DayId = "1603"
                        },
                        new
                        {
                            DayId = "1703"
                        },
                        new
                        {
                            DayId = "1803"
                        },
                        new
                        {
                            DayId = "1903"
                        },
                        new
                        {
                            DayId = "2003"
                        },
                        new
                        {
                            DayId = "2103"
                        },
                        new
                        {
                            DayId = "2203"
                        },
                        new
                        {
                            DayId = "2303"
                        },
                        new
                        {
                            DayId = "2403"
                        },
                        new
                        {
                            DayId = "2503"
                        },
                        new
                        {
                            DayId = "2603"
                        },
                        new
                        {
                            DayId = "2703"
                        },
                        new
                        {
                            DayId = "2803"
                        },
                        new
                        {
                            DayId = "2903"
                        },
                        new
                        {
                            DayId = "3003"
                        },
                        new
                        {
                            DayId = "3103"
                        },
                        new
                        {
                            DayId = "0104"
                        },
                        new
                        {
                            DayId = "0204"
                        },
                        new
                        {
                            DayId = "0304"
                        },
                        new
                        {
                            DayId = "0404"
                        },
                        new
                        {
                            DayId = "0504"
                        },
                        new
                        {
                            DayId = "0604"
                        },
                        new
                        {
                            DayId = "0704"
                        },
                        new
                        {
                            DayId = "0804"
                        },
                        new
                        {
                            DayId = "0904"
                        },
                        new
                        {
                            DayId = "1004"
                        },
                        new
                        {
                            DayId = "1104"
                        },
                        new
                        {
                            DayId = "1204"
                        },
                        new
                        {
                            DayId = "1304"
                        },
                        new
                        {
                            DayId = "1404"
                        },
                        new
                        {
                            DayId = "1504"
                        },
                        new
                        {
                            DayId = "1604"
                        },
                        new
                        {
                            DayId = "1704"
                        },
                        new
                        {
                            DayId = "1804"
                        },
                        new
                        {
                            DayId = "1904"
                        },
                        new
                        {
                            DayId = "2004"
                        },
                        new
                        {
                            DayId = "2104"
                        },
                        new
                        {
                            DayId = "2204"
                        },
                        new
                        {
                            DayId = "2304"
                        },
                        new
                        {
                            DayId = "2404"
                        },
                        new
                        {
                            DayId = "2504"
                        },
                        new
                        {
                            DayId = "2604"
                        },
                        new
                        {
                            DayId = "2704"
                        },
                        new
                        {
                            DayId = "2804"
                        },
                        new
                        {
                            DayId = "2904"
                        },
                        new
                        {
                            DayId = "3004"
                        },
                        new
                        {
                            DayId = "0105"
                        },
                        new
                        {
                            DayId = "0205"
                        },
                        new
                        {
                            DayId = "0305"
                        },
                        new
                        {
                            DayId = "0405"
                        },
                        new
                        {
                            DayId = "0505"
                        },
                        new
                        {
                            DayId = "0605"
                        },
                        new
                        {
                            DayId = "0705"
                        },
                        new
                        {
                            DayId = "0805"
                        },
                        new
                        {
                            DayId = "0905"
                        },
                        new
                        {
                            DayId = "1005"
                        },
                        new
                        {
                            DayId = "1105"
                        },
                        new
                        {
                            DayId = "1205"
                        },
                        new
                        {
                            DayId = "1305"
                        },
                        new
                        {
                            DayId = "1405"
                        },
                        new
                        {
                            DayId = "1505"
                        },
                        new
                        {
                            DayId = "1605"
                        },
                        new
                        {
                            DayId = "1705"
                        },
                        new
                        {
                            DayId = "1805"
                        },
                        new
                        {
                            DayId = "1905"
                        },
                        new
                        {
                            DayId = "2005"
                        },
                        new
                        {
                            DayId = "2105"
                        },
                        new
                        {
                            DayId = "2205"
                        },
                        new
                        {
                            DayId = "2305"
                        },
                        new
                        {
                            DayId = "2405"
                        },
                        new
                        {
                            DayId = "2505"
                        },
                        new
                        {
                            DayId = "2605"
                        },
                        new
                        {
                            DayId = "2705"
                        },
                        new
                        {
                            DayId = "2805"
                        },
                        new
                        {
                            DayId = "2905"
                        },
                        new
                        {
                            DayId = "3005"
                        },
                        new
                        {
                            DayId = "3105"
                        },
                        new
                        {
                            DayId = "0106"
                        },
                        new
                        {
                            DayId = "0206"
                        },
                        new
                        {
                            DayId = "0306"
                        },
                        new
                        {
                            DayId = "0406"
                        },
                        new
                        {
                            DayId = "0506"
                        },
                        new
                        {
                            DayId = "0606"
                        },
                        new
                        {
                            DayId = "0706"
                        },
                        new
                        {
                            DayId = "0806"
                        },
                        new
                        {
                            DayId = "0906"
                        },
                        new
                        {
                            DayId = "1006"
                        },
                        new
                        {
                            DayId = "1106"
                        },
                        new
                        {
                            DayId = "1206"
                        },
                        new
                        {
                            DayId = "1306"
                        },
                        new
                        {
                            DayId = "1406"
                        },
                        new
                        {
                            DayId = "1506"
                        },
                        new
                        {
                            DayId = "1606"
                        },
                        new
                        {
                            DayId = "1706"
                        },
                        new
                        {
                            DayId = "1806"
                        },
                        new
                        {
                            DayId = "1906"
                        },
                        new
                        {
                            DayId = "2006"
                        },
                        new
                        {
                            DayId = "2106"
                        },
                        new
                        {
                            DayId = "2206"
                        },
                        new
                        {
                            DayId = "2306"
                        },
                        new
                        {
                            DayId = "2406"
                        },
                        new
                        {
                            DayId = "2506"
                        },
                        new
                        {
                            DayId = "2606"
                        },
                        new
                        {
                            DayId = "2706"
                        },
                        new
                        {
                            DayId = "2806"
                        },
                        new
                        {
                            DayId = "2906"
                        },
                        new
                        {
                            DayId = "3006"
                        },
                        new
                        {
                            DayId = "0107"
                        },
                        new
                        {
                            DayId = "0207"
                        },
                        new
                        {
                            DayId = "0307"
                        },
                        new
                        {
                            DayId = "0407"
                        },
                        new
                        {
                            DayId = "0507"
                        },
                        new
                        {
                            DayId = "0607"
                        },
                        new
                        {
                            DayId = "0707"
                        },
                        new
                        {
                            DayId = "0807"
                        },
                        new
                        {
                            DayId = "0907"
                        },
                        new
                        {
                            DayId = "1007"
                        },
                        new
                        {
                            DayId = "1107"
                        },
                        new
                        {
                            DayId = "1207"
                        },
                        new
                        {
                            DayId = "1307"
                        },
                        new
                        {
                            DayId = "1407"
                        },
                        new
                        {
                            DayId = "1507"
                        },
                        new
                        {
                            DayId = "1607"
                        },
                        new
                        {
                            DayId = "1707"
                        },
                        new
                        {
                            DayId = "1807"
                        },
                        new
                        {
                            DayId = "1907"
                        },
                        new
                        {
                            DayId = "2007"
                        },
                        new
                        {
                            DayId = "2107"
                        },
                        new
                        {
                            DayId = "2207"
                        },
                        new
                        {
                            DayId = "2307"
                        },
                        new
                        {
                            DayId = "2407"
                        },
                        new
                        {
                            DayId = "2507"
                        },
                        new
                        {
                            DayId = "2607"
                        },
                        new
                        {
                            DayId = "2707"
                        },
                        new
                        {
                            DayId = "2807"
                        },
                        new
                        {
                            DayId = "2907"
                        },
                        new
                        {
                            DayId = "3007"
                        },
                        new
                        {
                            DayId = "3107"
                        },
                        new
                        {
                            DayId = "0108"
                        },
                        new
                        {
                            DayId = "0208"
                        },
                        new
                        {
                            DayId = "0308"
                        },
                        new
                        {
                            DayId = "0408"
                        },
                        new
                        {
                            DayId = "0508"
                        },
                        new
                        {
                            DayId = "0608"
                        },
                        new
                        {
                            DayId = "0708"
                        },
                        new
                        {
                            DayId = "0808"
                        },
                        new
                        {
                            DayId = "0908"
                        },
                        new
                        {
                            DayId = "1008"
                        },
                        new
                        {
                            DayId = "1108"
                        },
                        new
                        {
                            DayId = "1208"
                        },
                        new
                        {
                            DayId = "1308"
                        },
                        new
                        {
                            DayId = "1408"
                        },
                        new
                        {
                            DayId = "1508"
                        },
                        new
                        {
                            DayId = "1608"
                        },
                        new
                        {
                            DayId = "1708"
                        },
                        new
                        {
                            DayId = "1808"
                        },
                        new
                        {
                            DayId = "1908"
                        },
                        new
                        {
                            DayId = "2008"
                        },
                        new
                        {
                            DayId = "2108"
                        },
                        new
                        {
                            DayId = "2208"
                        },
                        new
                        {
                            DayId = "2308"
                        },
                        new
                        {
                            DayId = "2408"
                        },
                        new
                        {
                            DayId = "2508"
                        },
                        new
                        {
                            DayId = "2608"
                        },
                        new
                        {
                            DayId = "2708"
                        },
                        new
                        {
                            DayId = "2808"
                        },
                        new
                        {
                            DayId = "2908"
                        },
                        new
                        {
                            DayId = "3008"
                        },
                        new
                        {
                            DayId = "3108"
                        },
                        new
                        {
                            DayId = "0109"
                        },
                        new
                        {
                            DayId = "0209"
                        },
                        new
                        {
                            DayId = "0309"
                        },
                        new
                        {
                            DayId = "0409"
                        },
                        new
                        {
                            DayId = "0509"
                        },
                        new
                        {
                            DayId = "0609"
                        },
                        new
                        {
                            DayId = "0709"
                        },
                        new
                        {
                            DayId = "0809"
                        },
                        new
                        {
                            DayId = "0909"
                        },
                        new
                        {
                            DayId = "1009"
                        },
                        new
                        {
                            DayId = "1109"
                        },
                        new
                        {
                            DayId = "1209"
                        },
                        new
                        {
                            DayId = "1309"
                        },
                        new
                        {
                            DayId = "1409"
                        },
                        new
                        {
                            DayId = "1509"
                        },
                        new
                        {
                            DayId = "1609"
                        },
                        new
                        {
                            DayId = "1709"
                        },
                        new
                        {
                            DayId = "1809"
                        },
                        new
                        {
                            DayId = "1909"
                        },
                        new
                        {
                            DayId = "2009"
                        },
                        new
                        {
                            DayId = "2109"
                        },
                        new
                        {
                            DayId = "2209"
                        },
                        new
                        {
                            DayId = "2309"
                        },
                        new
                        {
                            DayId = "2409"
                        },
                        new
                        {
                            DayId = "2509"
                        },
                        new
                        {
                            DayId = "2609"
                        },
                        new
                        {
                            DayId = "2709"
                        },
                        new
                        {
                            DayId = "2809"
                        },
                        new
                        {
                            DayId = "2909"
                        },
                        new
                        {
                            DayId = "3009"
                        },
                        new
                        {
                            DayId = "0110"
                        },
                        new
                        {
                            DayId = "0210"
                        },
                        new
                        {
                            DayId = "0310"
                        },
                        new
                        {
                            DayId = "0410"
                        },
                        new
                        {
                            DayId = "0510"
                        },
                        new
                        {
                            DayId = "0610"
                        },
                        new
                        {
                            DayId = "0710"
                        },
                        new
                        {
                            DayId = "0810"
                        },
                        new
                        {
                            DayId = "0910"
                        },
                        new
                        {
                            DayId = "1010"
                        },
                        new
                        {
                            DayId = "1110"
                        },
                        new
                        {
                            DayId = "1210"
                        },
                        new
                        {
                            DayId = "1310"
                        },
                        new
                        {
                            DayId = "1410"
                        },
                        new
                        {
                            DayId = "1510"
                        },
                        new
                        {
                            DayId = "1610"
                        },
                        new
                        {
                            DayId = "1710"
                        },
                        new
                        {
                            DayId = "1810"
                        },
                        new
                        {
                            DayId = "1910"
                        },
                        new
                        {
                            DayId = "2010"
                        },
                        new
                        {
                            DayId = "2110"
                        },
                        new
                        {
                            DayId = "2210"
                        },
                        new
                        {
                            DayId = "2310"
                        },
                        new
                        {
                            DayId = "2410"
                        },
                        new
                        {
                            DayId = "2510"
                        },
                        new
                        {
                            DayId = "2610"
                        },
                        new
                        {
                            DayId = "2710"
                        },
                        new
                        {
                            DayId = "2810"
                        },
                        new
                        {
                            DayId = "2910"
                        },
                        new
                        {
                            DayId = "3010"
                        },
                        new
                        {
                            DayId = "3110"
                        },
                        new
                        {
                            DayId = "0111"
                        },
                        new
                        {
                            DayId = "0211"
                        },
                        new
                        {
                            DayId = "0311"
                        },
                        new
                        {
                            DayId = "0411"
                        },
                        new
                        {
                            DayId = "0511"
                        },
                        new
                        {
                            DayId = "0611"
                        },
                        new
                        {
                            DayId = "0711"
                        },
                        new
                        {
                            DayId = "0811"
                        },
                        new
                        {
                            DayId = "0911"
                        },
                        new
                        {
                            DayId = "1011"
                        },
                        new
                        {
                            DayId = "1111"
                        },
                        new
                        {
                            DayId = "1211"
                        },
                        new
                        {
                            DayId = "1311"
                        },
                        new
                        {
                            DayId = "1411"
                        },
                        new
                        {
                            DayId = "1511"
                        },
                        new
                        {
                            DayId = "1611"
                        },
                        new
                        {
                            DayId = "1711"
                        },
                        new
                        {
                            DayId = "1811"
                        },
                        new
                        {
                            DayId = "1911"
                        },
                        new
                        {
                            DayId = "2011"
                        },
                        new
                        {
                            DayId = "2111"
                        },
                        new
                        {
                            DayId = "2211"
                        },
                        new
                        {
                            DayId = "2311"
                        },
                        new
                        {
                            DayId = "2411"
                        },
                        new
                        {
                            DayId = "2511"
                        },
                        new
                        {
                            DayId = "2611"
                        },
                        new
                        {
                            DayId = "2711"
                        },
                        new
                        {
                            DayId = "2811"
                        },
                        new
                        {
                            DayId = "2911"
                        },
                        new
                        {
                            DayId = "3011"
                        },
                        new
                        {
                            DayId = "0112"
                        },
                        new
                        {
                            DayId = "0212"
                        },
                        new
                        {
                            DayId = "0312"
                        },
                        new
                        {
                            DayId = "0412"
                        },
                        new
                        {
                            DayId = "0512"
                        },
                        new
                        {
                            DayId = "0612"
                        },
                        new
                        {
                            DayId = "0712"
                        },
                        new
                        {
                            DayId = "0812"
                        },
                        new
                        {
                            DayId = "0912"
                        },
                        new
                        {
                            DayId = "1012"
                        },
                        new
                        {
                            DayId = "1112"
                        },
                        new
                        {
                            DayId = "1212"
                        },
                        new
                        {
                            DayId = "1312"
                        },
                        new
                        {
                            DayId = "1412"
                        },
                        new
                        {
                            DayId = "1512"
                        },
                        new
                        {
                            DayId = "1612"
                        },
                        new
                        {
                            DayId = "1712"
                        },
                        new
                        {
                            DayId = "1812"
                        },
                        new
                        {
                            DayId = "1912"
                        },
                        new
                        {
                            DayId = "2012"
                        },
                        new
                        {
                            DayId = "2112"
                        },
                        new
                        {
                            DayId = "2212"
                        },
                        new
                        {
                            DayId = "2312"
                        },
                        new
                        {
                            DayId = "2412"
                        },
                        new
                        {
                            DayId = "2512"
                        },
                        new
                        {
                            DayId = "2612"
                        },
                        new
                        {
                            DayId = "2712"
                        },
                        new
                        {
                            DayId = "2812"
                        },
                        new
                        {
                            DayId = "2912"
                        },
                        new
                        {
                            DayId = "3012"
                        },
                        new
                        {
                            DayId = "3112"
                        });
                });

            modelBuilder.Entity("Entities.Models.Tenant", b =>
                {
                    b.Property<string>("TenantId")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("TenantId");

                    b.ToTable("Tenants");

                    b.HasData(
                        new
                        {
                            TenantId = "Admin"
                        },
                        new
                        {
                            TenantId = "Test"
                        });
                });

            modelBuilder.Entity("Entities.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RefreshTokenExpiryTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");

                    b.HasData(
                        new
                        {
                            Id = "966246e1-c651-4d1e-9905-20ddb37d1608",
                            ConcurrencyStamp = "146c71db-eb27-43da-94a3-e9abd4198a38",
                            Name = "Viewer",
                            NormalizedName = "VIEWER"
                        },
                        new
                        {
                            Id = "9e8dd91e-ebad-452c-8ed1-820febe7a9f6",
                            ConcurrencyStamp = "98aaeeb3-8f22-4033-a0b5-8bf39047d44d",
                            Name = "Administrator",
                            NormalizedName = "ADMINISTRATOR"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("DayTenant", b =>
                {
                    b.HasOne("Entities.Models.Day", null)
                        .WithMany()
                        .HasForeignKey("DaysDayId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entities.Models.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantsTenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
